/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 untitled.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Scene(props) {
  const { nodes, materials } = useGLTF('/untitled.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0, -0.005, 0]} scale={[7.718, 7.718, 6.617]}>
        <mesh geometry={nodes.Plane.geometry} material={materials.Black} />
        <mesh geometry={nodes.Plane_1.geometry} material={materials.wood} />
        <mesh geometry={nodes.Plane_2.geometry} material={materials.gold} />
        <mesh geometry={nodes.Plane_3.geometry} material={materials.neonyelow} />
      </group>
      <group position={[-2.772, 6.41, 2.946]}>
        <mesh geometry={nodes.Cylinder001.geometry} material={materials.gold} />
        <mesh geometry={nodes.Cylinder001_1.geometry} material={materials.light} />
        <mesh geometry={nodes.Cylinder001_2.geometry} material={materials.PretoListraBranca} />
      </group>
      <mesh geometry={nodes.Copyright.geometry} material={materials.light} position={[7.332, 1.236, -6.067]} rotation={[0.84, 0, Math.PI / 2]} scale={0.095} />
      <mesh geometry={nodes.numbers.geometry} material={nodes.numbers.material} position={[1.907, 2.018, -3.593]} rotation={[0.254, 0.625, -0.155]} scale={0.057} />
      <group position={[1.907, 2.018, -3.593]} rotation={[2.892, -0.151, -2.921]} scale={[0.004, 0, 0.004]}>
        <mesh geometry={nodes.Cube001.geometry} material={materials.wood} />
        <mesh geometry={nodes.Cube001_1.geometry} material={materials.gold} />
        <mesh geometry={nodes.Cube001_2.geometry} material={materials['Dark Blue']} />
        <mesh geometry={nodes.Cube001_3.geometry} material={materials.UVMesa} />
        <mesh geometry={nodes.Cube001_4.geometry} material={materials.tablewood} />
      </group>
      <group position={[1.907, 2.018, -3.593]} rotation={[0, 0.631, 0]} scale={0.045}>
        <mesh geometry={nodes.Circle001.geometry} material={materials.gold} />
        <mesh geometry={nodes.Circle001_1.geometry} material={materials['Pallete Colors']} />
        <mesh geometry={nodes.Circle001_2.geometry} material={materials.Steel} />
      </group>
      <group position={[1.619, 2.08, -3.575]} rotation={[Math.PI / 2, 0, -0.631]} scale={0.005}>
        <mesh geometry={nodes.Mesh.geometry} material={materials.wood} />
        <mesh geometry={nodes.Mesh_1.geometry} material={materials.gold} />
        <mesh geometry={nodes.Mesh_2.geometry} material={materials.UVMesa} />
        <group position={[139.771, 818.011, 447.708]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[248.29, 301.634, 248.29]}>
          <mesh geometry={nodes.Circle002.geometry} material={materials.wood} />
          <mesh geometry={nodes.Circle002_1.geometry} material={materials.gold} />
          <mesh geometry={nodes.Circle002_2.geometry} material={materials.tablewood} />
        </group>
      </group>
      <mesh geometry={nodes.Roulette_Chair.geometry} material={materials.PretoListraBranca} position={[4.39, -0.033, 1.295]} rotation={[Math.PI / 2, 0, 1.456]} scale={0.002}>
        <mesh geometry={nodes.chair2.geometry} material={materials.PretoListraBranca} position={[-841.105, 861.256, 0]} rotation={[0, 0, 1.087]} />
        <mesh geometry={nodes.chair3.geometry} material={materials.PretoListraBranca} position={[-1601.967, 1292.951, 0]} rotation={[0, 0, 1.087]} />
        <mesh geometry={nodes.chair4.geometry} material={materials.PretoListraBranca} position={[-430.175, -751.927, 0]} rotation={[0, 0, -0.62]} />
      </mesh>
      <group position={[-2.116, 0, 0.137]} rotation={[0, 0.637, 0.014]} scale={[0.548, 0.048, 0.548]}>
        <mesh geometry={nodes.Cube005.geometry} material={materials.Black} />
        <mesh geometry={nodes.Cube005_1.geometry} material={materials.gold} />
        <mesh geometry={nodes.Cube005_2.geometry} material={materials['Dark Blue']} />
        <group position={[-0.638, -0.002, 2.736]} rotation={[-0.016, -0.209, 0]} scale={[1, 1, 1.001]}>
          <mesh geometry={nodes.Cube013.geometry} material={materials.Black} />
          <mesh geometry={nodes.Cube013_1.geometry} material={materials.gold} />
          <mesh geometry={nodes.Cube013_2.geometry} material={materials['Dark Blue']} />
        </group>
        <group position={[-1.052, 0.081, 5.272]} rotation={[-0.026, -0.329, 0]} scale={[1, 1, 1.001]}>
          <mesh geometry={nodes.Cube015.geometry} material={materials.Black} />
          <mesh geometry={nodes.Cube015_1.geometry} material={materials.gold} />
          <mesh geometry={nodes.Cube015_2.geometry} material={materials['Dark Blue']} />
        </group>
      </group>
      <group position={[-2.897, 2.117, 1.805]} rotation={[0, -1.119, 0]} scale={[1, 0.155, 1.079]}>
        <mesh geometry={nodes.Cylinder002.geometry} material={materials.Black} />
        <mesh geometry={nodes.Cylinder002_1.geometry} material={materials.gold} />
        <mesh geometry={nodes.Cylinder002_2.geometry} material={materials.neonyelow} />
        <mesh geometry={nodes.Cylinder002_3.geometry} material={materials['Dark Blue']} />
        <mesh geometry={nodes.Cylinder002_4.geometry} material={materials['Dark green']} />
        <mesh geometry={nodes.Handler.geometry} material={materials.gold} position={[0, -0.028, 0]} rotation={[0, 0, 0.002]} scale={[1.008, 1.002, 1.002]} />
      </group>
      <group position={[-5.012, 3.578, -6.512]} rotation={[0.207, 0.054, -0.424]} scale={1.807}>
        <mesh geometry={nodes.Mesh003.geometry} material={materials['Dart.001']} />
        <mesh geometry={nodes.Mesh003_1.geometry} material={materials['Dart.002']} />
        <mesh geometry={nodes.Mesh003_2.geometry} material={materials.Dart} />
        <mesh geometry={nodes.Mesh003_3.geometry} material={materials['Dart board']} />
      </group>
      <group position={[-5.823, 2.406, -5.192]} rotation={[-0.072, 0.101, -0.289]} scale={1.807}>
        <mesh geometry={nodes.Mesh028.geometry} material={materials['Dart.001']} />
        <mesh geometry={nodes.Mesh028_1.geometry} material={materials['Dart.002']} />
        <mesh geometry={nodes.Mesh028_2.geometry} material={materials.Dart} />
        <mesh geometry={nodes.Mesh028_3.geometry} material={materials['Dart board']} />
        <mesh geometry={nodes.Mesh028_4.geometry} material={materials['Dart board.002']} />
      </group>
      <group position={[-5.011, 3.581, -6.482]} rotation={[0.159, -0.42, -1.17]} scale={1.807}>
        <mesh geometry={nodes.Mesh035.geometry} material={materials['Dart.001']} />
        <mesh geometry={nodes.Mesh035_1.geometry} material={materials['Dart.002']} />
        <mesh geometry={nodes.Mesh035_2.geometry} material={materials.Dart} />
        <mesh geometry={nodes.Mesh035_3.geometry} material={materials['Dart board.002']} />
      </group>
      <group position={[-5.017, 3.578, -6.474]} scale={1.807}>
        <mesh geometry={nodes.Mesh001.geometry} material={materials['Dart.002']} />
        <mesh geometry={nodes.Mesh001_1.geometry} material={materials['Dart board']} />
        <mesh geometry={nodes.Mesh001_2.geometry} material={materials['Dart board.002']} />
        <mesh geometry={nodes.Mesh001_3.geometry} material={materials['Dart board.001']} />
        <group position={[-0.008, -0.077, 0.018]} rotation={[Math.PI / 2, 0, 0]} scale={0.045}>
          <mesh geometry={nodes.Mesh002.geometry} material={materials['Dart board.002']} />
          <mesh geometry={nodes.Mesh002_1.geometry} material={materials['Dart board.001']} />
        </group>
      </group>
      <group position={[-5.982, 1.148, -5.19]} scale={[0.23, 0.904, 0.23]}>
        <mesh geometry={nodes.Cylinder.geometry} material={materials.gold} />
        <mesh geometry={nodes.Cylinder_1.geometry} material={materials['Dark green']} />
        <mesh geometry={nodes.Cylinder_2.geometry} material={materials['Dart.002']} />
        <mesh geometry={nodes.Cylinder_3.geometry} material={materials.Dart} />
      </group>
    </group>
  )
}

useGLTF.preload('/untitled.gltf')
